# Generated by Django 4.2.4 on 2024-07-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachamodel', '0005_rename_diasriego_usuario_diasriego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='horaRiego',
            field=models.TimeField(default=0, max_length=200),
        ),
    ]
